import { Router } from 'express';
import { requireAuth } from '../../middleware/require-auth.js';
import { validateRequest as validate } from '../../middleware/validate-request.js';
import * as schema from '../../schemas/merchant.schema.js';
import * as catalogSchema from '../../schemas/catalog.schema.js';
import * as controller from '../../controllers/merchant.controller.js';
import * as productController from '../../controllers/product.controller.js';
import * as merchantOrderController from '../../controllers/merchant-order.controller.js';
import { merchantOrderParamsSchema, merchantOrderQuerySchema } from '../../schemas/order.schema.js';
import * as shipmentSchema from '../../schemas/shipment.schema.js';
import * as shipmentController from '../../controllers/shipment.controller.js';
const router = Router();
router.use(requireAuth);
router.get('/stores', controller.list);
router.post('/stores', validate('body', schema.createMerchantSchema), controller.create);
router.get('/stores/:merchantId', validate('params', schema.merchantParams), controller.get);
router.get('/stores/:merchantId/members', validate('params', schema.merchantParams), controller.members);
router.post('/stores/:merchantId/members', validate('params', schema.merchantParams), validate('body', schema.memberSchema), controller.addMember);
router.patch('/stores/:merchantId/members/:userId', validate('params', schema.memberParams), validate('body', schema.roleSchema), controller.updateMember);
router.delete('/stores/:merchantId/members/:userId', validate('params', schema.memberParams), controller.deleteMember);
router.get('/stores/:merchantId/products', validate('params', catalogSchema.sellerStoreParamsSchema), validate('query', catalogSchema.sellerProductQuerySchema), productController.sellerList);
router.post('/stores/:merchantId/products', validate('params', catalogSchema.sellerStoreParamsSchema), validate('body', catalogSchema.createProductSchema), productController.sellerCreate);
router.get('/stores/:merchantId/products/:productId', validate('params', catalogSchema.merchantProductParamsSchema), productController.sellerGet);
router.patch('/stores/:merchantId/products/:productId', validate('params', catalogSchema.merchantProductParamsSchema), validate('body', catalogSchema.updateProductSchema), productController.sellerUpdate);
router.post('/stores/:merchantId/products/:productId/submit', validate('params', catalogSchema.merchantProductParamsSchema), productController.sellerSubmit);
router.get('/stores/:merchantId/products/:productId/images', validate('params', catalogSchema.merchantProductParamsSchema), productController.sellerImages);
router.post('/stores/:merchantId/products/:productId/images', validate('params', catalogSchema.merchantProductParamsSchema), validate('body', catalogSchema.createProductImageSchema), productController.sellerCreateImage);
router.patch('/stores/:merchantId/products/:productId/images/:imageId', validate('params', catalogSchema.productImageParamsSchema), validate('body', catalogSchema.updateProductImageSchema), productController.sellerUpdateImage);
router.delete('/stores/:merchantId/products/:productId/images/:imageId', validate('params', catalogSchema.productImageParamsSchema), productController.sellerDeleteImage);
router.get('/stores/:merchantId/products/:productId/variants', validate('params', catalogSchema.merchantProductParamsSchema), productController.sellerVariants);
router.post('/stores/:merchantId/products/:productId/variants', validate('params', catalogSchema.merchantProductParamsSchema), validate('body', catalogSchema.createProductVariantSchema), productController.sellerCreateVariant);
router.patch('/stores/:merchantId/products/:productId/variants/:variantId', validate('params', catalogSchema.productVariantParamsSchema), validate('body', catalogSchema.updateProductVariantSchema), productController.sellerUpdateVariant);
router.patch('/stores/:merchantId/products/:productId/variants/:variantId/inventory', validate('params', catalogSchema.productVariantParamsSchema), validate('body', catalogSchema.inventorySchema), productController.sellerUpdateInventory);
router.get('/stores/:merchantId/orders', validate('params', merchantOrderParamsSchema.pick({ merchantId: true })), validate('query', merchantOrderQuerySchema), merchantOrderController.list);
router.get('/stores/:merchantId/orders/:merchantOrderId', validate('params', merchantOrderParamsSchema), merchantOrderController.get);
for (const action of ['accept', 'process', 'ready'] as const) {
	router.post(`/stores/:merchantId/orders/:merchantOrderId/${action}`, validate('params', merchantOrderParamsSchema), merchantOrderController.transition(action));
}
router.post('/stores/:merchantId/orders/:merchantOrderId/cancel', validate('params', merchantOrderParamsSchema), merchantOrderController.cancel);
router.get('/stores/:merchantId/orders/:merchantOrderId/shipment', validate('params', shipmentSchema.shipmentParamsSchema), shipmentController.get);
router.post('/stores/:merchantId/orders/:merchantOrderId/shipment', validate('params', shipmentSchema.shipmentParamsSchema), validate('body', shipmentSchema.createShipmentSchema), shipmentController.create);
router.patch('/stores/:merchantId/orders/:merchantOrderId/shipment', validate('params', shipmentSchema.shipmentParamsSchema), validate('body', shipmentSchema.updateShipmentSchema), shipmentController.update);
export default router;
